trigger: none
pr: none

variables:
- template: vars.yml

jobs:
- job: Clean subscription
  pool:
    vmImage: ubuntu-latest

  steps:
  - template: ./templates/template-clean-subscription.yml
    parameters:
      purgeTTL: $(purgeTTL)
      dryRun: $(dryRun)
      workingDirectory: ${{ variables.modulePath }}
      subscriptionCredential: $(subscription-credential)
      subscriptionId: $(subscriptionId)
      resourceGroupDeletePrefix: $(resourceGroupDeletePrefix)

